package com.walgreens.rawxmldatapuller.util;

import javax.crypto.SecretKeyFactory;
import javax.crypto.spec.PBEKeySpec;
import java.security.MessageDigest;
import java.security.SecureRandom;
import java.util.Base64;

/**
 * PBKDF2-SHA256 password hashing — zero external dependencies.
 * Stored format: {@code <iterations>:<base64-salt>:<base64-hash>}
 */
public final class PasswordUtil {

    private static final int    ITERATIONS = 310_000;
    private static final int    KEY_BITS   = 256;
    private static final int    SALT_BYTES = 16;
    private static final String ALGORITHM  = "PBKDF2WithHmacSHA256";

    private PasswordUtil() {}

    /** Hashes a plain-text password. Store the returned string as-is. */
    public static String hash(String password) {
        byte[] salt = new byte[SALT_BYTES];
        new SecureRandom().nextBytes(salt);
        byte[] hash = derive(password.toCharArray(), salt, ITERATIONS, KEY_BITS);
        return ITERATIONS + ":" + b64(salt) + ":" + b64(hash);
    }

    /** Returns {@code true} if {@code password} matches the stored hash. */
    public static boolean verify(String password, String stored) {
        if (stored == null || stored.isEmpty()) return false;
        String[] parts = stored.split(":", 3);
        if (parts.length != 3) return false;
        try {
            int    iterations = Integer.parseInt(parts[0]);
            byte[] salt       = Base64.getDecoder().decode(parts[1]);
            byte[] expected   = Base64.getDecoder().decode(parts[2]);
            byte[] actual     = derive(password.toCharArray(), salt, iterations, expected.length * 8);
            return MessageDigest.isEqual(actual, expected);
        } catch (Exception e) {
            return false;
        }
    }

    /**
     * Generates a cryptographically random temporary password that satisfies
     * the application's strength requirements (8+ chars, upper, lower, digit, special).
     */
    public static String generateTempPassword() {
        String upper   = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
        String lower   = "abcdefghijklmnopqrstuvwxyz";
        String digits  = "0123456789";
        String special = "!@#$%^";
        String all     = upper + lower + digits + special;

        SecureRandom rng = new SecureRandom();
        char[] chars = new char[12];
        // Guarantee at least one from each required category
        chars[0] = upper.charAt(rng.nextInt(upper.length()));
        chars[1] = lower.charAt(rng.nextInt(lower.length()));
        chars[2] = digits.charAt(rng.nextInt(digits.length()));
        chars[3] = special.charAt(rng.nextInt(special.length()));
        for (int i = 4; i < 12; i++) chars[i] = all.charAt(rng.nextInt(all.length()));

        // Fisher-Yates shuffle
        for (int i = 11; i > 0; i--) {
            int j = rng.nextInt(i + 1);
            char tmp = chars[i]; chars[i] = chars[j]; chars[j] = tmp;
        }
        return new String(chars);
    }

    private static byte[] derive(char[] pwd, byte[] salt, int iter, int keyBits) {
        try {
            PBEKeySpec spec = new PBEKeySpec(pwd, salt, iter, keyBits);
            byte[] result = SecretKeyFactory.getInstance(ALGORITHM).generateSecret(spec).getEncoded();
            spec.clearPassword();
            return result;
        } catch (Exception e) {
            throw new RuntimeException("Password hashing failed", e);
        }
    }

    private static String b64(byte[] data) {
        return Base64.getEncoder().encodeToString(data);
    }

    /**
     * Run this from IntelliJ (right-click → Run 'PasswordUtil.main()') to generate
     * password hashes for database seeding.
     */
    public static void main(String[] args) {
        String[][] users = {
                // { username, password, fullName, role }
                { "admin", "Admin@1234", "Administrator", "ADMIN" },
        };

        System.out.println("-- Generated by PasswordUtil — paste into init.sql");
        System.out.println("USE rxpuller_auth;");
        System.out.println();
        for (String[] u : users) {
            String hash = hash(u[1]);
            System.out.printf(
                    "INSERT INTO users (username, password_hash, full_name, role) VALUES ('%s', '%s', '%s', '%s');%n",
                    u[0], hash, u[2], u[3]);
        }
    }
}
